### ISSUE TITLE
Generate Open Graph / social media meta tags

### ISSUE THREAD

**Issue by tlaundal** [ivodolenc/sveltekit-statiko#4]
### Request Description

Inspired by [this tweet](https://twitter.com/leeerob/status/1619743437577912321) and coming config for NextJS:
![Fnp77OCXEAUFIgp](https://user-images.githubusercontent.com/817001/215347343-18c58bfc-04b6-428b-a37e-d6ccd3e92cf9.jpg)

It would be nice if statico could generate some of the open graph tags.
A few tags can often be static for the whole page: `og:type`, `og:locale`, `og:site_name`, `fb:pages`, `fb:app_id` to name a few.

And some tags would be nice to have some utilities for easy creation, like dynamic `og:url`.

For my sites I like to set my `<title>` to "Site Name | Page Name" and `og:title` to just "Page Name". Perhaps statico could provide an utility for this. In the same way to duplicate `og:description` and `<meta name="description" />` as well.

### Alternative Solutions

Statiko currently doesn't have any utilities for use in application code, but I think it would complement the project nicely.

### Additional Details

This is all just to get the idea out of my head. I might take a stab at implementing something like this for Statiko later.

**Comment by tlaundal** [comment]
For the `og:url` and `canonical` tags you are quite right. One caveat, which I just found the solution for, is that you need to specify `kit.prerender.origin` in `svelte.config.js` for this to work on pre-rendered pages (unless they are hydrated).

Regarding customizing the pages, this does not work quite as expected, as sveltekit will merge the contents of `<svelte:head>` from `+page.svelte` and `+layout.svelte` into `app.html`. If you define `<meta property="og:title" .../>` in all three, you will get it three times in your rendered `<head>`. The only exception I've found here is `<title>` which is deduplicated, but only across the `.svelte` files. So you will still get duplicate `<title>` if you also define it in `app.html`.

I do of course think it would be nice with some functionality to resolve this problem of having default values that are customized to different pages.

I can also see some use for automatically populating tags which are similar (`og:title` could fall back to `<title>` if it is not set), and cropping images to correct proportions for `og:image` and `twitter:image`.

**Comment by ivodolenc** [comment]
Statiko is intended for SvelteKit + adapter static, i.e. static generation (Designed for `SSG` rendering mode).

For [prerendering](https://kit.svelte.dev/docs/page-options#prerender), all you need to do is to create `+layout.ts` (or .js) file inside `src/routes/` dir and set `prerender = true`.

```js
// src/routes/+layout.ts

export const prerender = true
```

There is no duplicate meta tags or similar issues when exporting for production.

Also, all tags defined inside `+layout.svelte` (inside `<svelte:head>`) is fallback tags i.e. global default tags.

They only change if you specifically set them on other pages.

**Comment by tlaundal** [comment]
> There is no duplicate meta tags or similar issues when exporting for production.
> 
> Also, all tags defined inside `+layout.svelte` (inside `<svelte:head>`) is fallback tags i.e. global default tags.

Have you tried this? It doesn't seem to work this way for me. See [this example repo (zip)](https://github.com/ivodolenc/sveltekit-statiko/files/10550830/sveltekit-merges-heads.zip).

I would also like to point out that Statiko is very useful also for projects that are not completely static! But it is probably good that the project has a specific target audience.

**Comment by tlaundal** [comment]
I can see why you don't want to include this in Statiko. My original reason for thinking it might be nice was because of Statiko's knowledge of `siteUrl`. However with the `kit.prerender.origin` config option I discovered earlier this doesn't apply anymore.

I don't think Svelte/Kit will try to implement deduplication of arbitrary head tags, as it's somewhat hard to decide which element's to deduplicate and not. `<meta name="og:title" .... />` should be deduplicated, but `<meta name="creator" ... />` can legitimately appear multiple times.
